### ISSUE TITLE
Getting the fresh devel and running

### ISSUE THREAD

**Issue by RudoRoemer** [erickmartins/pdb2movie#8]
Getting a fresh devel and running 

aquarius tmp>python pdb2movie/pdb2movie.py 2B5E_FH.pdb 
---------------------------------------------------------------
pdb2movie: cleaning the PDB file
----------------------------------------------------------------
Traceback (most recent call last):
  File "pdb2movie/pdb2movie.py", line 128, in <module>
    clean_file=cleanpdb.cleanPDB(args,exec_folder)
  File "/home/physics/phsht/tmp/pdb2movie/cleanpdb.py", line 96, in cleanPDB
    inputfile=open(args.pdbfile[0],'r')
IOError: [Errno 2] No such file or directory: '2B5E_FH.pdb'

whle the previous version works. Is this an end-of-line error somewhere?

_Originally posted by @RudoRoemer in https://github.com/RudoRoemer/pdb2movie/pull/6#issuecomment-743803075_

**Comment by james-panayis** [comment]
This should now be fixed - it is now no-longer (incorrectly) assumed that the pdbfile's full path is given (see pull request #9 ) :)

**Comment by RudoRoemer** [comment]
More problems, see comments on the pull request.

**Comment by james-panayis** [comment]
Should be fixed! See the latest pull request #10 .

**Comment by RudoRoemer** [comment]
All fixed. Thanks.

**Comment by james-panayis** [comment]
This can be closed now :)
